/********************************************************/
/********************************************************/
/*********     Author : Ahmed el.shazly   ***************/
/*********     Layer  : MHAL              ***************/
/*********     SWC    : ADC               ***************/
/*********     Date   : 3/10/2023         ***************/
/********************************************************/
/********************************************************/

#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_
typedef enum
{
	ADC_REF_AREF,
	ADC_REF_AVCC,
	ADC_REF_INTERNAL,

}Adc_ReferenceType;


typedef enum
{
	ADC_SINGLE_ENDED_CHANNEL_ADC0,
	ADC_SINGLE_ENDED_CHANNEL_ADC1,
	ADC_SINGLE_ENDED_CHANNEL_ADC2,
	ADC_SINGLE_ENDED_CHANNEL_ADC3,
	ADC_SINGLE_ENDED_CHANNEL_ADC4,
	ADC_SINGLE_ENDED_CHANNEL_ADC5,
	ADC_SINGLE_ENDED_CHANNEL_ADC6,
	ADC_SINGLE_ENDED_CHANNEL_ADC7,

	ADC_DIFFERENTIAL_CHANNEL_ADC0_ADC0_10X,
	ADC_DIFFERENTIAL_CHANNEL_ADC1_ADC0_10X,
	ADC_DIFFERENTIAL_CHANNEL_ADC0_ADC0_200X,
	ADC_DIFFERENTIAL_CHANNEL_ADC1_ADC0_200X,

	ADC_DIFFERENTIAL_CHANNEL_ADC2_ADC2_10X,
	ADC_DIFFERENTIAL_CHANNEL_ADC3_ADC2_10X,
	ADC_DIFFERENTIAL_CHANNEL_ADC2_ADC2_200X,
	ADC_DIFFERENTIAL_CHANNEL_ADC3_ADC2_200X,

	ADC_DIFFERENTIAL_CHANNEL_ADC0_ADC1_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC1_ADC1_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC2_ADC1_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC3_ADC1_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC4_ADC1_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC5_ADC1_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC6_ADC1_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC7_ADC1_1X,

	ADC_DIFFERENTIAL_CHANNEL_ADC0_ADC2_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC1_ADC2_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC2_ADC2_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC3_ADC2_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC4_ADC2_1X,
	ADC_DIFFERENTIAL_CHANNEL_ADC5_ADC2_1X,

    ADC_CHANNEL_1_22_V,
    ADC_CHANNEL_GND

}Adc_ChannelType;



typedef enum
{
	ADC_PRESCALER_2,
	ADC_PRESCALER_4,
	ADC_PRESCALER_8,
	ADC_PRESCALER_16,
	ADC_PRESCALER_32,
	ADC_PRESCALER_64,
	ADC_PRESCALER_128,
}Adc_PrescalerType;


typedef enum
{
	ADC_AUTO_TRIGGER_OFF,
	ADC_AUTO_TRIGGER_FREE_RUNNING,
	ADC_AUTO_TRIGGER_ANAL_COMP,
	ADC_AUTO_TRIGGER_EXTI0,
	ADC_AUTO_TRIGGER_TIM0_COMP,
	ADC_AUTO_TRIGGER_TIM0_OVF,
	ADC_AUTO_TRIGGER_TIMB_COMP,
	ADC_AUTO_TRIGGER_TIM1_OVF,
	ADC_AUTO_TRIGGER_TIM1_CAP

}Adc_TriggerType;

typedef struct
{
	Adc_ReferenceType reference;
	Adc_TriggerType autoTrigger;
	Adc_PrescalerType prescaler;
} Adc_ConfigurationType;

#define ADC_U32TIME_OUT  50000UL

#endif
